### ISSUE TITLE
why is depext OCaml 4.02.1+ only?

### ISSUE THREAD

**Issue by avsm** [ocaml/opam-depext#1]
It's much better than `opam-installext`, but the compiler version restriction stops it from replacing it (e.g. in the Travis scripts)

**Comment by AltGr** [comment]
I think I just couldn't resist the `match with exception` syntax, but it should be straight-forward to backport.

**Comment by AltGr** [comment]
Fixed by d7ce7fa971eabfa4b569a19d0ba9efe5b1170799

**Comment by avsm** [comment]
Ha! Yes it's frustrating to have to maintain backcompat. I think that we can now replace installext in Travis with this, right? Move it to the OCaml org?

**Comment by samoht** [comment]
could be nice to also use it in Travis CI skeleton: https://github.com/ocaml/ocaml-travisci-skeleton/issues/21

**Comment by avsm** [comment]
and also add it as a base package in the default switches so it's always around?

**Comment by samoht** [comment]
that means making `cmdliner` a base package as well. no special opinion on this, so why not.

**Comment by avsm** [comment]
hm got point. we dont want those to grow too much, but it's a very useful feature.

**Comment by AltGr** [comment]
Not sure it's a good idea ; base package means you can't normally upgrade it. I'd rather wait until we have proper support integrated in OPAM.

But switch "recommended" packages, that could get installed as roots by default when you switch, without becoming "base" packages, why not.
