### ISSUE TITLE
Quoted OCaml package names causes the string "No packages found." to be passed to apt-get

### ISSUE THREAD

**Issue by kevin1** [ocaml/opam-depext#100]
Users can pass a list of packages to depext:

    $ opam depext core utop

Putting this in quotes makes it fail in a strange way:

```
$ opam depext "core utop"
# Detecting depexts using flags: armv6l linux debian
# The following system packages are needed:
#  - No
#  - packages
#  - found.
The following command needs to be run through "sudo":
    apt-get install No packages found.
Allow ? [Y/n] 
```

If I say yes, depext will actually run `$ apt-get install No packages found.`

Admittedly, this is an edge case. I encountered it by accidentally writing `opam depext "$my_package_list"` (with quotes) in a shell script.

What's interesting is that simply passing a nonexistent package name gives different behavior:

```
$ opam depext foobar
# Detecting depexts using flags: armv6l linux debian
[ERROR] No package named foobar found.
[ERROR] No package named foobar found.
# No extra OS packages requirements found.
# All required OS packages found.
```

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
