### ISSUE TITLE
Fix archlinux distribution id on 1.1.2

### ISSUE THREAD

**Issue by brnbrnrd** [ocaml/opam-depext#102]
I had this error using `opam 2.0,0~rc` on archlinux with `opam-depext.1.1.2`.
```
# Packages matching: installed & name-match(depext)
# No matches found
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=arch, os-family=archlinux
# No extra OS packages requirements found.
Fatal error: exception File "depext.ml", line 256, characters 13-19: Assertion failed
make: *** [Makefile:62: build-deps] Error 2
```

Commit https://github.com/ocaml/opam-depext/pull/101/commits/b8ef9f5055d86f7dc39b99b8a03a1c8bdab0d9ee should fix the problem.

Related commits https://github.com/ocaml/opam-depext/commit/23abbd0b95510e1f6d999555e47aba8d94df403a and https://github.com/ocaml/opam-depext/commit/f2ca8890e4ff30e984d62411e66f9f4dc9343de3.

Related PR #101 (aborted because no PR for tags).

**Comment by nitrotm** [comment]
As a quick hack if depext is not up-to-date:

`OPAMVAR_os_family=arch some-build-command`

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
