### ISSUE TITLE
opam-depext fails to install on macOS / OCaml 4.07 / opam 2.0

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml/opam-depext#104]
```
❯ ~ opam install opam-depext                  
The following actions will be performed:
  ∗ install opam-depext 1.1.2

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[opam-depext.1.1.2] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 

#=== ERROR while installing opam-depext.1.1.2 =================================#
/Users/ec/.opam/plugins/bin/opam-depext does not exist.


<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ ∗ install opam-depext 1.1.2
└─ 
╶─ No changes have been performed
```

I thought that perhaps it was failing to create the directory, but it still failed, even after `mkdir -p /Users/ec/.opam/plugins/bin`.

**Comment by rjbou** [comment]
Log is not really helping here: As installation fails, opam recover and clean process performs a remove of the package it was installing, which leads to remove a not yet existing link (plugin specific). And this error hide the real error report.
Can you launch again the install on verbose mode `-vvv`, it'll display all command (and their results), and help to locate the one failing and the real problem.
Thanks for reporting!

**Comment by rjbou** [comment]
@ELLIOTTCABLE  Any news on this?

**Comment by ELLIOTTCABLE** [comment]
Hmmmm. I am no longer able to reproduce, so closing, for now. `¯\_(ツ)_/¯`
