### ISSUE TITLE
Missing OpenSUSE 15 (leap) support

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam-depext#109]
According to https://github.com/ocaml/opam-repository/pull/13077 OpenSUSE 15.0 has `opensuse-leap` as value for `os-distribution` and thus doesn't work well with opam packages that suppose `opensuse`

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
