### ISSUE TITLE
Unnecessary request for escalation of privileges

### ISSUE THREAD

**Issue by deliciouslytyped** [ocaml/opam-depext#116]
I got this on NixOS while trying to build something:

```
The following command needs to be run through "sudo":
    echo Skipping system update on this platform.
```

That seems like a pretty pointless thing to need privilege escalation for.
After that I even failed to escalate with sudo and everything still succeeded anyway.

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
