### ISSUE TITLE
doesn't work with <package>.opam

### ISSUE THREAD

**Issue by samoht** [ocaml/opam-depext#12]
If a repository has multiple `*.opam` files, `opam depext` will just fail as it won't find the root `opam` file.

**Comment by AltGr** [comment]
I don't understand: opam-depext doesn't ever deal with opam files, it just calls opam to query the dependencies. Did you mean this for  [opam-publish](https://github.com/OCamlPro/opam-publish/issues/24) ?

**Comment by samoht** [comment]
Wooops sorry it's indeed the wrong issue tracker...

**Comment by shonfeder** [comment]
Would it make sense to extend depext to be able to work with opam files? This can be handy for installing system deps for a package you're going to pin or install locally. E.g., in my CI I currently have a step like this:

```
opam show ./themis-render.opam --field=depends:     | awk '{ print $1 }' | xargs opam depext
```

This work fine, but it seems inelegant.

Given that `opam install foo` and `opam install ./foo.opam` both do the expected thing, it seem reasonable to assume `opam depext foo` and `opam depext ./foo.opam` would as well. I understand if this is outside the scope of the intended use, but I wanted to note that it seems like a logical usecase from my perspective.

**Comment by rjbou** [comment]
@shonfeder depext will be embedded in install process in opam 2.1.

**Comment by shonfeder** [comment]
Oh nice. Even better. Thanks @rjbou!
