### ISSUE TITLE
opam depext --with-test/with-doc shouldn't try to get test/doc depexts recursively

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam-depext#121]
There is a weird error in the following PR https://github.com/ocaml/opam-repository/pull/14175:
```
[ERROR] No solution for eqaf.0.4: The following dependencies couldn't be met:
          - eqaf → crowbar → xmldiff → xmlm < 1.3.0 → ocaml < 4.06.0
              base of this switch (use `--unlock-base' to force)
Command failed: opam list --readonly --with-test --external  --resolve=eqaf.0.4 returned 20
```
opam-depext fails with this when called with `opam depext --with-test` (added in https://github.com/ocaml/opam-depext/pull/120) but `crowbar` only depends on `xmldiff` "with-test". So it seems that `opam list --with-test` doesn't have the same behaviour as `opam install --with-test` as it looks for every tests dependencies recursively and not just in the given package as `opam install --with-test` does.

**Comment by rjbou** [comment]
@AltGr Is it volunteer to not have the same behavior on `with-test` variable propagation between install & list operations ?

**Comment by AltGr** [comment]
probably not, it's historical. We need to hurry with integration of depext handling to avoid these consistency issues

**Comment by AltGr** [comment]
but the issue would be in `opam list`, since that's what `depext` calls to get the list of tags to resolve.

**Comment by AltGr** [comment]
(more precisely, `opam list --resolve=PKGS --with-test`)

**Comment by rjbou** [comment]
> but the issue would be in opam list, since that's what depext calls to get the list of tags to resolve.

Yes, if an opam issue there is, i.e. should `--resolve` comply with `opam install` results ?

**Comment by kit-ty-kate** [comment]
Should I open an opam issue instead?

**Comment by rjbou** [comment]
@kit-ty-kate PR opened!
