### ISSUE TITLE
Allow passing brew options in the depexts field of an opam file

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-depext#125]
cf. https://github.com/ocaml/opam-repository/issues/13078

**Comment by UnixJunkie** [comment]
For example, on osx in the conf-gnuplot package, we should say:
```
brew install gnuplot --with-qt
```
instead of
```
brew install gnuplot
```

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
