### ISSUE TITLE
Issues with variants in MacPorts

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam-depext#128]
I added MacPorts solutions to a few opam conf packages. See: (https://github.com/ocaml/opam-repository/pull/16912)

One issues is that depext doesn't seem to handle variants like "gtk3 +quartz" ins a consistent manner. When printing what to install, gtk3 and +quartz are listed on separate lines, but when sorting packages alphabetically it seems to treat them as one. I guess this is just not handled at all explicitly - maybe it should.

It somehow works as is, but it looks like it might break any day by a change.

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). Please open the issue in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
