### ISSUE TITLE
Passing "answer yes" or "don't ask questions" option down to OS package manager

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml/opam-depext#130]
Many package managers have an option to answer questions on also installing dependencies with yes automatically - like "-y" for MacPorts. It would be nice if depext would have such an option it would pass down the the respective system package managers (where they support it).

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). It is present in [opam.2.1.0~alpha2](https://github.com/ocaml/opam/pull/4168).
Thanks!
