### ISSUE TITLE
opam-depext doesn't recognise libgmp-dev or libssl-dev

### ISSUE THREAD

**Issue by ozmos** [ocaml/opam-depext#139]
I am trying to install the dependencies for ocaml.org but run into the following error when running `opam depext ocamlorg`:
```
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=linuxmint, os-family=ubuntu
# The following system packages are needed:
libgmp-dev
libssl-dev
Sorry, don't know how to install packages on your ubuntu system
```
System info:

Processor | Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz
-- | --
Memory | 16345MB (3004MB used)
Machine Type | Desktop
Operating System | Linux Mint 20.1
Date/Time | Thu 08 Apr 2021 18:43:59

I have followed the 'up and running' steps on ocaml.org and intsalled libgmp-dev and libssl-dev

**Comment by dra27** [comment]
This works with opam 2.1, if you're happy to install a pre-release (you just run `opam install conf-gmp conf-libssl` in 2.1 - there's no need to run the depext command separately).

Alternatively, you can persuade opam-depext to work by adding `OPAMVAR_os_family=debian` to the call: i.e. `OPAMVAR_os_family=debian opam depext -i conf-gmp conf-libssl`.

**Comment by ozmos** [comment]
Thanks I'll give that a shot.

**Comment by avsm** [comment]
I'm sure Linux Mint used to work with the opam 2.0 depext though; perhaps something has changed in the /etc/os-release variables upstream.

**Comment by dra27** [comment]
They changed in Mint 18 (2016), it would appear: https://bugs.launchpad.net/linuxmint/+bug/1641491

**Comment by ozmos** [comment]
Thanks, solved by @dra27
