### ISSUE TITLE
alternatives in `depexts` field?

### ISSUE THREAD

**Issue by c-cube** [ocaml/opam-depext#140]
opam 2.1 made me confront the harsh reality that `conf-rust` is a bit lacking (as it's now mandatory that it works well), at least on arch.

the problem is that I do have rust, but it's installed via `rustup`. There are several ways to install rust on arch, so I'd like to specify something like:

```
if rustup is installed: run `rustup toolchain add stable`
if cargo is installed: do nothing

then, check it worked by running `rustc --version` and `cargo --version`
```

I don't find any docs so I'm not sure if this is possible at all.

**Comment by AltGr** [comment]
My feeling is that this is really outside the scope of opam: "depexts" allow it to somewhat interact with the whole system, but in a limited and pre-defined way, in particular it's never expected to run package-specified commands that might affect the outside of the current switch.

The depexts feature has been designed from the start to allow manual bypassing for such cases though. The current interface may be lacking, requiring you to find your way in a series of yes/no questions, but it does allow to skip installation through the package manager, wait while you manually install the package, skip detection if required, and record the exception in order not to prompt you again about this package.

Alternatively, you may tell users of `rustup` to run `opam install conf-rust --no-depexts` (possibly through the `messages:` or `post-messages:` fields).

**Comment by c-cube** [comment]
I guess it'll have to suffice, thank you.

**Comment by dra27** [comment]
There are two possible features in the mid-term plan which may help here, but not soon:

- Windows has a very complicated depext story, having multiple ways of acquiring and installing depexts (at least on macOS the choice between brew or macports is usually fixed on any given machine). There's an idea to generalise the "system" to a thing called a build environment where the present depext is simply the "system" build environment. Other build environments would include, say, building switches in docker containers - i.e. the idea is that you attach a switch to a build environment.
- A possible simpler feature is to provide more configuration to depext as _what_ the package manager is - this includes the possibility of enabling multiple depext tools. At the moment, your os, arch etc is used to select which depext system to use - that might be generalised further. With this idea, opam would not _automatically_ use `rustup` but it might be possible to configure opam to be able to drive rustup/cargo.
