### ISSUE TITLE
By default, do not try to install the depexts if the the required packages are already installed

### ISSUE THREAD

**Issue by samoht** [ocaml/opam-depext#15]
The current behaviour (always install depext) could still be available using `--force`

**Comment by samoht** [comment]
That behaviour is annoying because it is slow and it requires to be sudo even if that's not needed.

**Comment by AltGr** [comment]
Yes. But we need to add check commands for every package manager :) -- just a matter of doing that.

**Comment by samoht** [comment]
Why is this closed?

**Comment by AltGr** [comment]
Ah, sorry, misunderstood this as the "detect installed _system_ packages before trying to install" stuff, which was implemented ; while you meant _ocaml_ packages. The former does help though (if you're up-to-date you won't need sudo anymore) -- but it's at a different level.

**Comment by UnixJunkie** [comment]
Might be related to https://github.com/ocaml/opam-repository/issues/4076

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
