### ISSUE TITLE
More generic distribution IDs 

### ISSUE THREAD

**Issue by juergenhoetzel** [ocaml/opam-depext#21]
Currently packagers have to define `depexts` for each existing distribution, even though they all use the same naming conventions and packages managers.

For example:

```
  depexts: [
    [["debian"] ["libssl-dev"]]
    [["mageia"] ["openssl-devel"]
    [["fedora"]] ["openssl-devel"]
    [["centos"] ["openssl-devel"]]
  ]
```

It would be nice to have some more general TAGS like `"fedora-based"`

**Comment by AltGr** [comment]
We already have "bsd" that regroups all of "freebsd", "openbsd", "dragonfly", etc. , so that should be easy to do. Opening a larger discussion on the design of these tags in the OPAM issue tracker though.

**Comment by avsm** [comment]
The issue that's rearing its head is that we need to discriminate by version now, as several packages are only available in a particular revision of a distribution.  Remaining fine grained is the only way to do that...

**Comment by AltGr** [comment]
Indeed, but we can provide both options (given that a system will always have the `centos` _and_ the `fedora-based` tags, packages can use any)

**Comment by avsm** [comment]
@AltGr agreed

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
