### ISSUE TITLE
Package detection is broken on Ubuntu and Debian

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-depext#22]

**Comment by UnixJunkie** [comment]
cannot even detect m4

**Comment by UnixJunkie** [comment]
Try on an Ubuntu 'opam depext ctypes'

**Comment by samoht** [comment]
Can you please be a bit more constructive in your bug reports? It works fine with Ubunty 14.04 and depext 0.5. Thanks!

``` shell
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-24-generic x86_64)

$ opam depext ctypes
# Detecting depexts using flags: x86_64 linux ubuntu
# The following system packages are needed:
#  - m4
Not running as root, the following command will be run through "sudo":
    apt-get install -qq -yy m4
# OS packages installation successful
$ opam-depext --version
0.5
```

**Comment by UnixJunkie** [comment]
https://github.com/ocaml/opam-depext/pull/23

**Comment by UnixJunkie** [comment]
Do you really don't have m4 on your machine?
dpkg -l m4
will tell you
I guess you have it since you are a developper

**Comment by UnixJunkie** [comment]
It's broken on Ubuntu 12.04.5 LTS
(without the fix I propose)

**Comment by samoht** [comment]
So I guess the title "this is just broken on Ubuntu" is wrong. You mean that the detection of already installed packages is broken and this is quite different. Anyway, having a working detection of already installed packages will speed up things, thanks for the fix.

**Comment by UnixJunkie** [comment]
Yeah, sorry for the quick and dirty description I gave.
Can I tell opam to use my fixed version of depext ?

**Comment by avsm** [comment]
I still don't understand what this report is about, or if there is a patch associated (what 'fixed version of depext' are you referring to?).  Could you please edit the title and give a summary of the problem, @UnixJunkie?

**Comment by UnixJunkie** [comment]
I sent a pull request to opam-depext with my proposed fix

**Comment by UnixJunkie** [comment]
I was using depext 0.5 from opam when I discovered it doesn't work properly in some cases

**Comment by samoht** [comment]
> Can I tell opam to use my fixed version of depext ?

As usual, use pins:

```
opam pin add depext https://github.com/UnixJunkie/opam-depext.git#fix_debian_and_ubuntu_pkg_detection
```
