### ISSUE TITLE
brew may require additional dependencies interactively (?)

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam-depext#3]
Trying to run depext for `ocaml-top` (with debug) gave me the following:

```
+ "brew" "install" "gtksourceview" "libxml2"
gtksourceview: XQuartz is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/xquartz

You can download from:
  https://xquartz.macosforge.org
cairo: XQuartz is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/xquartz
```

and a few like that, before it failed. How can we automatically handle that ?

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (from [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
