### ISSUE TITLE
When presenting a solution, indicate which opam packages are responsible

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam-depext#34]
Right now, when asking for `depext` to install system packages for an opam package, I see something like:

```
# Detecting depexts using flags: x86_64 osx homebrew
# The following system packages are needed:
#  - openssl
#  - pkg-config
```

It would be nice to have that list annotated with the opam packages that are responsible for the necessity of installing these packages.

**Comment by AltGr** [comment]
Noted. This would need a patch in upstream opam though, as these are simply returned in bulk by a call to opam.

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
