### ISSUE TITLE
Bad detection of "virtual" package in Debian

### ISSUE THREAD

**Issue by ghost** [ocaml/opam-depext#48]
Hi,  with the current `opam-repository`, where `ocamlfind` depends on `conf-ncurses`, any call to `opam depext ...` try to install the Debian package `ncurses-dev`, even if it was previously installed.

The reason is that `ncurses-dev` is not a real package, but only a "virtual package" that is provided by at least the "real" package `libncurses5-dev`. The current implementation of `get_installed_packages` on Debian is not able to detect this.

After asking some Debian guys, it seems there is no trivial fix, other than:
- look for all providers: 

```
apt-cache search --names-only '^ncurses-dev$'
```
- test if one of the returned packages is installed (with the actual `dpkg-query` command).

Another fix would be not to use "virtual" package in `opam-repository`.

@avsm It seems that you chose to use `ncurses-dev` rather than `libncurses5-dev`, any reason for this ? (https://github.com/ocaml/opam-repository/commit/0290831) In the current debian stable, there is only one provider for `ncurses-dev`. I suppose it is only here for compatibility with older Debian release. But I can't tell which one.

By the way, I just re-read https://github.com/ocaml/opam-repository/pull/4962#issuecomment-147649350 And after looking more carefully to the `ocamlfind` code, it seems that the `ncurses-dev` package is only required because `ocamlfind` is linked with the `-custom` flag.

Another workaround, would be to use `./configure -no-custom` in the `ocamlfind` package. I suppose the "custom bytecode executable" is not critical when `ocamlfind` is compiled within opam, as we won't remove the original `ocamlrun` anyway.

Any thoughts ?

**Comment by AltGr** [comment]
This is already being discussed on #44 ; @mato has an interesting solution, but it requires pulling an additional package as an initial step.

> In the current debian stable, there is only one provider for ncurses-dev. I suppose it is only here for compatibility with older Debian release. But I can't tell which one.

If I understand correctly, these virtual packages are there as much for backwards-compat as forward-compat: they allow to specify an ncurses dependency without requiring a specific version.
