### ISSUE TITLE
Tries to use `su -c foo` on OSX

### ISSUE THREAD

**Issue by ijc** [ocaml/opam-depext#51]
This code:

```
let sudo_run_command ~su ~interactive os distribution cmd =
[...]
        if su then
          ["su"; "-c"; Printf.sprintf "%S" (String.concat " " cmd)]
        else
          "sudo"::cmd
```

Will try and run essentially `su -c command` however on 10.11.5:

```
$ su -c 'echo hello world'
su: illegal option -- c
usage: su [-] [-flm] [login [args]]
```

To be valid it needs a username (the OSX `su(1)` only mentions this implicitly in the `EXAMPLES` section):

```
$ su ijc -c 'echo hello world'
Password:
hello world
```

I'm not sure if this is something which changed since an earlier OSX or maybe this code is never run because everyone has `sudo` (which takes precedence over `su`) installed?

I was debugging some CI issues which I thought might be related to the environment provided by `sudo` or `su` so after reading `sudo_run_command` I added the commands which I inferred it would run to my `circle.yml` as an experiment and discovered the behaviour, I've not actually observed this in practice via an `opam depext` invocation because I have `sudo` installed.

**Comment by AltGr** [comment]
Ah, interesting, thanks for reporting. You can try to reproduce by forcing use of `su` through the `--su` flag. In this case we probably should use `su root -c ...` ?

**Comment by ijc** [comment]
I get:

```
MACOSX_DEPLOYMENT_TARGET=10.10 OPAMROOT="/Users/distiller/vpnkit/_build/opam" OPAMYES=1 OPAMCOLORS=1 OPAMBUILDTEST=1 opam depext --su -d -u slirp
opam-depext: unknown option `--su', did you mean either `-u' or `-s' ?
```

So probably my version isn't new enough to even claim to support it.
