### ISSUE TITLE
linuxbrew support?

### ISSUE THREAD

**Issue by struktured** [ocaml/opam-depext#55]
I would love to add linuxbrew support to the list. This would prevent me from ever needing sudo when setting up ocaml. Seeing as you already support homebrew, is linuxbrew doable?

**Comment by dsheets** [comment]
Support is possible. You will need to modify https://github.com/ocaml/opam-depext/blob/master/depext.ml to add a case for linuxbrew to the various matches. Also, the linuxbrew package names would need to be added to the opam-repository for packages with depexts.

**Comment by UnixJunkie** [comment]
Is linuxbrew really production-ready?

**Comment by struktured** [comment]
@UnixJunkie it is close in quality to the original brew, but is a bit less maintained. I stopped having to use linuxbrew so I'm less concerned about this issue than I used to be. Feel free to close with *wontfix* status.

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
