### ISSUE TITLE
 on a centos: opam depext should use the instructions for fedora

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-depext#56]
if no centos instructions are present.
Maybe same thing for redhat.
I can help with the testing of the feature if needed.
Thanks!
F.

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
