### ISSUE TITLE
Adopt a robust build system

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/opam-depext#57]
[This is really not](https://github.com/ocaml/opam-depext/blob/5ede4efc77c9a7bc0d482ac8c301834057abd538/opam#L13-L18). 

In particular it fails the `safe-string` migration of `cmdliner` 1.0.0 in 4.01.0 switches. See https://github.com/ocaml/opam-repository/pull/8588#issuecomment-283512705

**Comment by AltGr** [comment]
Haha, you could have said just "adopt a build system" :)
Indeed, this needs to be done

**Comment by avsm** [comment]
There is a good reason for the existing build system -- depext cannot depend on ocamlfind. #59 goes some way towards removing the build commands from the `opam` file itself

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
