### ISSUE TITLE
support cmdliner 1.0.0

### ISSUE THREAD

**Issue by ivg** [ocaml/opam-depext#58]
Recently you pushed a constrained to the opam repository, that requires cmdliner 0.9.8, disallowing all other versions. As my experiments show, opam-depext works perfectly fine with old versions of cmdliner, as well as cmdliner.1.0.0. Mostly because, the changes affect manpage generation, that is not used in depext at all.

So, is there any reason, that I miss, why you pushed this constraint?
If not, can you please, lift it, it blocks our upgrade to 1.0.0. (Probably, it will block anyone who wants to use cmdliner.1.0.0 and depext at the same time).

**Comment by dbuenzli** [comment]
Fundamentally nothing has to be done except add `bytes` and `result` on compilers that do not support it to the ["build system"](https://github.com/ocaml/opam-depext/issues/57). However we discussed this yesterday with @avsm and it seems he rather wants to vendor the dep as cmdliner's install now depend on `ocamlfind` and `ocamlfind` does sport depexts.

**Comment by ivg** [comment]
I've made further investigations and updated the issue description. It looks like that the constraint is overcautious, as depext works perfectly fine with the old and the new interfaces.

**Comment by dbuenzli** [comment]
> So, is there any reason, that I miss, why you pushed this constraint?

I did push it https://github.com/ocaml/opam-repository/pull/8611. It is overcautious in the sense that the build of `depext` failed only on 4.01 in the CI. However as mentioned with `cmdliner.1.0.0`, `depexts` can no longer `depexts` the `m4` of `ocamlfind` as `cmdliner` itself now depends on `ocamlfind`. So that may not be overcautious in the end.

**Comment by avsm** [comment]
I've now cut a release of depext of 1.0.3 that vendors cmdliner into this repo, so that depext is itself entirely dependency-free from an OPAM perspective.
