### ISSUE TITLE
depext should check ID_LIKE variable in os-release (Linux)

### ISSUE THREAD

**Issue by suchipi** [ocaml/opam-depext#63]
I'm using a Fedora-based distribution with the following in `/etc/os-release`:
```
NAME=Korora
VERSION="25 (Gurgle)"
ID=korora
ID_LIKE=fedora
VERSION_ID=25
PRETTY_NAME="Korora 25 (Gurgle)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:kororaproject:korora:25"
HOME_URL="https://kororaproject.org/"
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
```

`opam depext --flags` outputs the following:
```
# Depexts flags detected on this system: x86_64 linux korora
```

It'd be nice if it detected it as `fedora` (using ID_LIKE).

ID_LIKE is documented [here](https://www.freedesktop.org/software/systemd/man/os-release.html). tl;dr it's the same format as ID, but represents something that the distribution behaves like (fedora in my case, since my distro is based on fedora).

**Comment by AltGr** [comment]
This is actually probably a solution to #56 too: thanks for the idea.

**Comment by DimStar77** [comment]
> ID_LIKE is documented here. tl;dr it's the same format as ID, but represents something that the distribution behaves like (fedora in my case, since my distro is based on fedora).

nitpick: ID_LIKE is not the same format as ID, but a LIST of IDs

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
