### ISSUE TITLE
Some Darwin users have both brew and port but prefer port

### ISSUE THREAD

**Issue by maverickwoo** [ocaml/opam-depext#71]
https://github.com/ocaml/opam-depext/blob/cdc210e8217f6d682de65248dff1ad63484c2d52/depext.ml#L93-L96

The above logic hardcodes a preference for homebrew over macports, which is fine for the most part, but I would love to see a `--use-flags` (or a more appropriately named) argument that allows the user to provide the flags manually.

Thank you very much for your consideration.

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
