### ISSUE TITLE
Can't pass in/override flags

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/opam-depext#72]
I would appreciate if there was a way to override autodetection and pass in my own flags to `depext`. This is similar to #71 but more general.

My usecase is that I am building an image on one Docker base image (Debian) and would like to deploy it on another one (Alpine) but to get it to run I need to dump the Alpine depexts on the Debian image.

If there is interest, I could do a PR.

**Comment by AltGr** [comment]
Thanks for offering to help. This would indeed be a very useful feature, and a PR would be welcome!

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
