### ISSUE TITLE
Parseable format

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/opam-depext#73]
Currently `depext`, if not doing the installation by itself outputs the package list in a human readable format, but this format is not great if you want to process it.

So I could think of multiple ways to solve the issue:

1. Dump the install commands it would run, so they can be saved to a file and `exec`'d
2. Dump the list of packages in an format like JSON or S-Expressions
3. Dump the list of packages just as a space/newline spearated list

That way I could avoid having to drop the `#` comments from the depext output and to drop the leading `-` as well. Let me know if you prefer one solution or the other, I can do a PR if desired.

**Comment by AltGr** [comment]
Indeed, there is no good reason for the current format of `opam depext -l` : a pure list, one per line, would do the job and be easier to read. And the headers can be put to stderr if we want to keep them. I can see many cases where an option to dump the commands could be useful, too, but that could be slightly more tricky (we normally detect what is already installed to issue only the install commands that are needed).

If you have time to write a PR for this, that would be very much appreciated. Thanks!

**Comment by Leonidas-from-XIV** [comment]
You're right, printing the headers to stderr and outputting one line per dependency is a very good approach that will allow both humans and machines to read it.
