### ISSUE TITLE
"opam install depext" fails on macOS 10.12.6

### ISSUE THREAD

**Issue by jensgerlach** [ocaml/opam-depext#75]
The issues appears repeatedly.
Even with a clean install of 'brew' (1.3.1) and 'opam' (1.2.2).

```$ opam install depext
The following actions will be performed:
  ∗  install depext 1.0.5

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] https://opam.ocaml.org/archives/depext.1.0.5+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Processing  1/1: [depext: make]
#=== ERROR while installing depext.1.0.5 ======================================#
# opam-version 1.2.2
# os           darwin
# command      install -m 0755 /Users/jens/.opam/system/build/depext.1.0.5/opam-depext /Users/jens/.opam/system/bin/opam-depext
# path         /Users/jens/.opam/system/build/depext.1.0.5
# exit-code    127
# env-file     /Users/jens/.opam/log/log-57039-d8a4ae.env
# stdout-file  /Users/jens/.opam/log/log-57039-d8a4ae.out
# stderr-file  /Users/jens/.opam/log/log-57039-d8a4ae.err



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install depext 1.0.5```

**Comment by dbuenzli** [comment]
Could you please give the output of `echo $PATH` and `type install`

**Comment by jensgerlach** [comment]
Your request made me look critically look at all the directories in PATH.
I have deleted a couple of old directories from PATH and now it works!
Thanks!

**Comment by jensgerlach** [comment]
That was a bit too quick, sorry. While 'opam install depext' now works, I have now the problem
calling it:
 
$ opam depext frama-c

```Fatal error: exception # opam-version    1.2.2
# os              darwin
opam: "execvpe" failed on opam-depext: No such file or directory
````

Here is the requested output
```
$ echo $PATH
/Users/jens/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:.

$  type install
install is /usr/bin/install```

**Comment by dbuenzli** [comment]
> /Users/jens/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:.

Even though it seems to be the correct order I would highly suggest to remove that `.` from your PATH, see [here](https://github.com/ocaml/opam-repository/issues/10064#issuecomment-323202164). 

Regarding your problem does `eval $(opam config env) && opam depext frama-c` help ?

**Comment by jensgerlach** [comment]
I removed `.` from PATH but the problem persists.
However,  `eval $(opam config env) && opam depext frama-c` seems to work.

**Comment by dbuenzli** [comment]
> However, eval $(opam config env) && opam depext frama-c seems to work.

So there's no problem, as you can see in your PATH the `opam` bin directory of your switch is not listed, so it can't find the `opam-depext` binary. You need to have `eval $(opam config env)` in your shell for `opam` to work. Try rerunning `opam init` (here using opam v2 so the output may be different):

```
=-=- Required setup - please read -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

  In normal operation, opam only alters files within ~/.opam.

  However, to best integrate with your system, some environment variables
  should be set. If you allow it to, this initialisation step will update
  your bash configuration by adding the following line to ~/.profile:

    test -r /Users/dbuenzli/.opam/opam-init/init.sh && . /Users/dbuenzli/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

  Otherwise, every time you want to access your opam installation, you will
  need to run:

    eval `opam env`

  You can always re-run this setup with 'opam init' later.
```

**Comment by jensgerlach** [comment]
Thanks a lot!!

**Comment by AltGr** [comment]
> However, eval $(opam config env) && opam depext frama-c seems to work.

Note that `opam depext` searches in the updated `PATH` in the upcoming 2.0 release, so the `eval` won't be needed anymore.

**Comment by dbuenzli** [comment]
I think this can be closed.

**Comment by jensgerlach** [comment]
Agreed!
