### ISSUE TITLE
could be faster

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-depext#78]
Last time I looked at the code, we do several calls to the package manager while it would be possible
to do the same thing with less calls.
I can try to look into it some day.

**Comment by UnixJunkie** [comment]
the code has evolved but this is still the case for the rpm-based distros

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
