### ISSUE TITLE
only latest package version is used to select depexts

### ISSUE THREAD

**Issue by avsm** [ocaml/opam-depext#8]
ctypes.0.4.0 doesnt include a libffi depext, but installing ctypes.0.3.4 does need it.  depext currently only selects depexts from the latest version I think.  Needs a smarter solver interface to find out what would actually be installed via a dry run of some sort, and then find depexts from those packages specifically?

See e.g.:
http://www.recoil.org/~avsm/opam-bulk/logs/local-ubuntu-14.04-ocaml-4.01.0/raw/async_ssl.html#bottom

**Comment by AltGr** [comment]
Indeed, `opam list` only outputs the latest versions, the solver isn't involved. We would need to add an option to `list` to compute a real solution from an empty set of installed packages, somewhat like `opam-admin resolve` does, so we could get on with those packages.
