### ISSUE TITLE
On Fedora, successfull installation of `pkgconfig` makes `rpm -q` fail

### ISSUE THREAD

**Issue by mauny** [ocaml/opam-depext#80]
Fedora 26 uses `pkgconf-pkg-config` as an alternative to `pkgconfig`, as mentioned [here](https://fedoraproject.org/wiki/Fedora_26_talking_points#pkgconf_as_system_pkg-config_implementation).

When `depext` needs to install or check `pkgconfig` on F26, it fails even though `yum` correctly installs `pkgconf-pkg-config` in lieu of `pkgconfig`: the test used *after* installation (`rpm -q pkgconfig`) fails.
 
According to file `depext.ml` (line 214), Fedora seems to be the only distribution for which `depext` double-checks (`yum install -y`, then `rpm -q`) that the package installation has been successful.

Yet, if installation fails, `yum install` returns a non-zero status, which should be sufficient. Unless I am missing something, a simple fix could be to suppress the call to `rpm -q`.

**Comment by kit-ty-kate** [comment]
The ```rpm -q``` comes from this issue: https://github.com/ocaml/opam-depext/issues/9
I'm not sure how to fix that properly. I'll dig into that.

**Comment by marmarek** [comment]
I hit the same issue. Alternative solution to removing that check, is to use `rpm -q --whatprovides` instead of `rpm -q`.
