### ISSUE TITLE
depext should let us special-case versions of a distribution

### ISSUE THREAD

**Issue by gasche** [ocaml/opam-depext#82]
In https://github.com/ocaml/opam-repository/pull/10514#issuecomment-338386797, @Armael would like to give a different external dependency for a package depending on whether Centos6 and Centos7 is used.

This is a reasonable need that will occur more and more often as opam gets older, and we start supporting more versions of the same distribution -- package renames are infrequent but still inevitably happen.

I would propose that depext makes several tags available, `"distro"` and `"distro.version"`; a Centos6 system would be concerned both `"centos"` and `"centos.6" depexts`, for example.

**Comment by dbuenzli** [comment]
@gasche head there https://github.com/ocaml/opam/issues/3058

**Comment by AltGr** [comment]
Yup this has just been handled and will be integrated in beta5 :)
