### ISSUE TITLE
Fails on AppVeyor

### ISSUE THREAD

**Issue by Chris00** [ocaml/opam-depext#97]
I've been trying to enable AppVeyor for the [FreeTDS bindings](https://github.com/Chris00/ocaml-freetds).  To that aim, the OPAM file contains a `depexts` asking to [install `mingw64-x86_64-freetds`](https://github.com/Chris00/ocaml-freetds/blob/master/freetds.opam#L38).  However, [that fails](https://ci.appveyor.com/project/Chris00/ocaml-freetds-b1mk5/build/1.0.13#L335).  This is the right package however and [installing it before the build](https://github.com/Chris00/ocaml-freetds/blob/master/appveyor.yml#L17) works [fine](https://ci.appveyor.com/project/Chris00/ocaml-freetds-b1mk5/build/1.0.14#L360).  The [warnings at the beginning](https://ci.appveyor.com/project/Chris00/ocaml-freetds-b1mk5/build/1.0.14#L14) may possibly provide a clue to the failure.

**Comment by AltGr** [comment]
I can't seem to access your Appveyor links (they all return a page `Project not found or access denied.`). However, I don't believe `opam-depext` has the code to install cygwin packages just yet ? So the best it could do in that case is list to you the expected "system packages" that need to be installed...

**Comment by Chris00** [comment]
> I don't believe opam-depext has the code to install cygwin packages just yet 

Then it should signal it properly because [what one sees](https://ci.appveyor.com/project/Chris00/ocaml-freetds/build/1.0.70#L335) looks like it is trying to perform the install and fails.

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
